### PR TITLE
Replace flake8 with pylint

### PR DESCRIPTION
**Pull request by nir0s**
* Add `.pylintrc`
* Add pylint config to CI workflow and tox.
* Fix linting issues. For more info, see the commit message for https://github.com/python-distro/distro/commit/85c52b85c7ca8ec02770d04c90eb9cd4527b410a
* Remove py27 linting. It's EOL. Not sure if that makes sense right now, given that we test on 27. However, I'm not sure we should lint for it. Thoughts?

### CODE REVIEW

**Comment by jdufresne** [comment]
> Remove py27 linting. It's EOL. Not sure if that makes sense right now, given that we test on 27. However, I'm not sure we should lint for it. Thoughts?

I think we should remove EOL Pythons. I've done so in PR #281.

**Comment by sethmlarson** [comment]
Isn't flake8 more complete than pylint? I've not seen projects moving from flake8 -> pylint, usually the other way.

**Comment by jdufresne** [comment]
FWIW, most projects I have worked on choose flake8 over pylint. So it is my personal choice as well. (But only that, personal)

**Comment by hartwork** [comment]
@nir0s what is the motivation behind choosing pylint over flake8?

**Comment by nir0s** [comment]
Yeah, I was making assumptions here. I personally moved away from flake8 in different projects because I felt like it has better reporting.

However, I'm not strongly opinionated about this.

**Comment by nir0s** [comment]
I'm gonna close it. It's not worth a discussion AFAIC.

**Pull request closed without merging**
