### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by nir0s**
Could benefit us by focusing PR notifications on maintainers

### CODE REVIEW

**Comment by nir0s** [comment]
Thoughts?

**Comment by sethmlarson** [comment]
I'm eh on a global policy for pings, I'm already following the repository after all :) Usually I use `CODEOWNERS` to protect/solicit reviews from a select group of individuals rather than "everyone".

**Comment by nir0s** [comment]
Yeah, though that's what usually frightens me. Not everyone who joins an OS org is a "maintainer" per-se. Then you get reviews where you don't want them.

**Comment by nir0s** [comment]
I guess I'm going to close this until we feel the pain :)

**Pull request closed without merging**
